name: Compile binaries
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  linux-x86:
    runs-on: ubuntu-latest
    container: node:14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build module
      run: |
        npm ci --ignore-scripts
        npm run build -- --release
        npm run buildJs

    - name: Package module
      run: |
        npm run package

    - name: Upload to S3
      env:
        ALI_ACCESS_KEY_ID: ${{ secrets.ALI_ACCESS_KEY_ID }}
        ALI_SECRET_ACCESS_KEY: ${{ secrets.ALI_SECRET_ACCESS_KEY }}
      run: |
        npm run upload



  mac-x86:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable

    - name: Build module
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.13
      run: |
        npm ci --ignore-scripts
        npm run build -- --release
        npm run buildJs

    - name: Package module
      run: |
        npm run package

    - name: Upload to S3
      env:
        ALI_ACCESS_KEY_ID: ${{ secrets.ALI_ACCESS_KEY_ID }}
        ALI_SECRET_ACCESS_KEY: ${{ secrets.ALI_SECRET_ACCESS_KEY }}
      run: |
        npm run upload

  mac-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        target: aarch64-apple-darwin
        toolchain: nightly
        override: true

    - name: Select SDK
      run: |
        SDK=$(xcodebuild -showsdks -json | jq -r '.[] | .canonicalName' | grep '^macosx' | tail -n 1)
        echo "SDKROOT=$(xcrun -sdk $SDK --show-sdk-path)" >> $GITHUB_ENV

    - name: Build & package module
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.1
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --target aarch64-apple-darwin
        npm run buildJs
        sed -i.bak 's/"package_name":.*/"package_name": "{platform}-arm64-{node_napi_label}-{libc}.tar.gz",/' package.json
        npm run package

    - name: Upload to S3
      env:
        ALI_ACCESS_KEY_ID: ${{ secrets.ALI_ACCESS_KEY_ID }}
        ALI_SECRET_ACCESS_KEY: ${{ secrets.ALI_SECRET_ACCESS_KEY }}
      run: |
        npm run upload
